// export const deckCard = [
//   { spades: 6 },
//   { spades: 7 },
//   { spades: 8 },
//   { spades: 9 },
//   { spades: 10 },
//   { spades: 11 },
//   { spades: 12 },
//   { spades: 13 },
//   { spades: 14 },
//
//   { hearts: 6 },
//   { hearts: 7 },
//   { hearts: 8 },
//   { hearts: 9 },
//   { hearts: 10 },
//   { hearts: 11 },
//   { hearts: 12 },
//   { hearts: 13 },
//   { hearts: 14 },
//
//   { diamonds: 6 },
//   { diamonds: 7 },
//   { diamonds: 8 },
//   { diamonds: 9 },
//   { diamonds: 10 },
//   { diamonds: 11 },
//   { diamonds: 12 },
//   { diamonds: 13 },
//   { diamonds: 14 },
//
//   { clubs: 6 },
//   { clubs: 7 },
//   { clubs: 8 },
//   { clubs: 9 },
//   { clubs: 10 },
//   { clubs: 11 },
//   { clubs: 12 },
//   { clubs: 13 },
//   { clubs: 14 },
// ];

export const deckCard = [
  { suit: 'Черви', rank: 6 },
  { suit: 'Черви', rank: 7 },
  { suit: 'Черви', rank: 8 },
  { suit: 'Черви', rank: 9 },
  // { suit: 'Черви', rank: 10 },
  // { suit: 'Черви', rank: 11 },
  // { suit: 'Черви', rank: 12 },
  // { suit: 'Черви', rank: 13 },
  // { suit: 'Черви', rank: 14 },
  { suit: 'Бубны', rank: 6 },
  { suit: 'Бубны', rank: 7 },
  { suit: 'Бубны', rank: 8 },
  { suit: 'Бубны', rank: 9 },
  // { suit: 'Бубны', rank: 10 },
  // { suit: 'Бубны', rank: 11 },
  // { suit: 'Бубны', rank: 12 },
  // { suit: 'Бубны', rank: 13 },
  // { suit: 'Бубны', rank: 14 },
  { suit: 'Трефы', rank: 6 },
  { suit: 'Трефы', rank: 7 },
  { suit: 'Трефы', rank: 8 },
  { suit: 'Трефы', rank: 9 },
  // { suit: 'Трефы', rank: 10 },
  // { suit: 'Трефы', rank: 11 },
  // { suit: 'Трефы', rank: 12 },
  // { suit: 'Трефы', rank: 13 },
  // { suit: 'Трефы', rank: 14 },
  { suit: 'Пики', rank: 6 },
  { suit: 'Пики', rank: 7 },
  { suit: 'Пики', rank: 8 },
  { suit: 'Пики', rank: 9 },
  // { suit: 'Пики', rank: 10 },
  // { suit: 'Пики', rank: 11 },
  // { suit: 'Пики', rank: 12 },
  // { suit: 'Пики', rank: 13 },
  // { suit: 'Пики', rank: 14 },
];
